services:
  php:
    build: ./php
    volumes:
      - ..:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://symfony:symfony@postgres:5432/symfony?serverVersion=16&charset=utf8
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d symfony"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  cron:
    image: alpine:3.20
    volumes:
      - ..:/var/www/html
      - ./cron/crontab:/etc/crontabs/root:ro
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache php82-cli php82-phar php82-openssl php82-ctype php82-iconv php82-json php82-mbstring php82-curl && crond -f -l 2"]
    depends_on:
      - php

volumes:
  pgdata: {}
